import * as React from 'react'
import Navbar from './components/navbar'

import { ChakraProvider } from '@chakra-ui/react'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ChakraProvider>
      <Navbar />
      <body className={inter.className}>{children}</body>
    </ChakraProvider>
  )
}
